[package]
name = "grep-regex"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Default regex engine implementation for grep-like programs."

[dependencies]
grep-matcher = { path = "../grep-matcher" }
regex-automata = { version = "0.4", default-features = false, features = ["std", "meta", "nfa", "hybrid", "perf"] }
regex-syntax = "0.8"
bstr = "1"
log = "0.4"

[features]
default = []
pcre2 = []
